# before using this, don't forget to clone tpm
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

unbind r
bind r source-file ~/.tmux.conf

bind | split-window -h
bind - split-window -v

set -g prefix2 C-s

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle


run '~/.tmux/plugins/tpm/tpm'

# Status bar settings
set -g status-right "#[fg=#282a36]#[bg=#ff79c6] #($HOME/.tmux/plugins/tmux/scripts/battery.sh) #[fg=#282a36]#[bg=#ffb86c] #($HOME/.tmux/plugins/tmux/scripts/weather_wrapper.sh true true '' false) "
set -g status-position top
